name: "Lint"

# Run these these whenever ...
on:
  pull_request: # ... a PR is opened / updated
  merge_group: # ... the PR is added to the merge queue
  push:
    branches:
      - 20250908_namelist_4_CI_TEST

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Pace
        uses: actions/checkout@v5
        with:
          submodules: 'false'

      - name: "Checkout NDSL"
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'
          repository: jjuyeonkim/ndsl
          path: pace/NDSL
          ref: 20250908_namelist_2

      - name: "Checkout pyFV3"
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'
          repository: jjuyeonkim/pyfv3
          path: pace/pyFV3
          ref: 20250908_namelist_2

      - name: "Checkout pySHiELD"
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'
          repository: jjuyeonkim/pyshield
          path: pace/pySHiELD
          ref: 20250908_namelist_2

      - name: "Git log checks"
        run: |
          git -C ${GITHUB_WORKSPACE}/pace log -1
          git -C ${GITHUB_WORKSPACE}/pace/NDSL log -1
          git -C ${GITHUB_WORKSPACE}/pace/pyFV3 log -1
          git -C ${GITHUB_WORKSPACE}/pace/pySHiELD log -1

      - name: Step Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Only restore (don't save) caches on PRs. New caches created from PRs won't be
      # accessible from other PRs, see workflows/create-cache.yaml.
      - uses: actions/cache/restore@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit_${{ env.pythonLocation }}_${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run lint via pre-commit
        run: pre-commit run --all-files
