name: "pace main unit tests"

# Run these these whenever ...
on:
  workflow_call: # ... called from a downstream repo
    inputs:
      component_trigger:
        type: boolean
        default: true
        required: false
      component_name:
        type: string
        default: ''
        required: false
  pull_request: # ... a PR is opened / updated
  merge_group:  # ... the PR is added to the merge queue
  push:
    branches:
      - 20250908_namelist_3_CI_TEST
      - 20250908_namelist_2

# cancel running jobs if theres a newer push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# TODO: Revert tests back to GFDL (not jjuyeonkim) after merging
# https://github.com/NOAA-GFDL/NDSL/issues/64
# For now, manually doing checkouts of NDSL, pyFV3, pySHiELD because
# at this point, I don't know of a better way to checkout with
# a specific branch name
jobs:
  pace_main_unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: "External trigger: Checkout pace/develop"
        if: ${{ inputs.component_trigger }}
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'
          repository: jjuyeonkim/pace
          path: pace
          ref: 20250908_namelist_3
          fetch-depth: 0

      - name: "Janice's Sanity Check 1"
        run: |
          echo "GITHUB_WORKSPACE: " ${GITHUB_WORKSPACE}
          echo "inputs.component_name: " ${{inputs.component_name}}
          echo "pwd: "
          pwd
          echo "ls :"
          ls

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install mpi (MPICH flavor)
        run: pip install mpich

      - name: "External trigger: Remove existing component in pace/develop"
        if: ${{ inputs.component_trigger }}
        run: rm -rf ${GITHUB_WORKSPACE}/pace/${{inputs.component_name}}

      - name: Checkout out hash that triggered CI
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          path: pace/${{inputs.component_name}}

      - name: "Janice's Sanity Check 2"
        run: |
          echo "pwd: "
          pwd
          echo "ls :"
          ls *
          git -C . log -1
          git remote -v

      - name: "Janice's Sanity Check 2b"
        run: |
          echo "ls ${GITHUB_WORKSPACE}/pace"
          ls ${GITHUB_WORKSPACE}/pace
          git -C ${GITHUB_WORKSPACE}/pace log -1

      - name: "Janice's Sanity Check 3"
        run: |
          echo "pwd: "
          pwd
          echo "ls ${GITHUB_WORKSPACE}/NDSL"
          ls ${GITHUB_WORKSPACE}/NDSL
          git -C ${GITHUB_WORKSPACE}/NDSL log -1
          cd ${GITHUB_WORKSPACE}/NDSL
          git remote -v

      - name: "Janice's Sanity Check 4"
        run: |
          echo "pwd: "
          pwd
          echo "ls ${GITHUB_WORKSPACE}/pyFV3"
          ls ${GITHUB_WORKSPACE}/pyFV3
          git -C ${GITHUB_WORKSPACE}/pyFV3 log -1
          cd ${GITHUB_WORKSPACE}/pyFV3
          git remote -v

      - name: "Janice's Sanity Check 5"
        run: |
          echo "pwd: "
          pwd
          echo "ls ${GITHUB_WORKSPACE}/pySHiELD"
          ls ${GITHUB_WORKSPACE}/pySHiELD
          git -C ${GITHUB_WORKSPACE}/pySHiELD log -1
          cd ${GITHUB_WORKSPACE}/pySHiELD
          git remote -v

      - name: "Janice's look out submodule 20250908_namelist_2 branches"
        run: |
          cd ${GITHUB_WORKSPACE}/pace
          pwd
          echo "ls ${GITHUB_WORKSPACE}/pace"
          git -C . log -1
          git -C ./pySHiELD log -1
          git -C ./pyFV3 log -1
          git -C ./NDSL log -1
          # TODO Add checkouts if this is okay?

      - name: Install packages
        run: |
          cd ${GITHUB_WORKSPACE}/pace
          pip install .[test]

      - name: Print versions
        run: |
          python --version
          pip --version
          pip list

      - name: Prepare input files
        run: |
          cd ${GITHUB_WORKSPACE}/pace
          mkdir tests/main/input
          python examples/generate_eta_files.py tests/main/input

      - name: Run tests
        run: |
          cd ${GITHUB_WORKSPACE}/pace
          python -m pytest -x tests/main

      - name: Run baroclinic test case
        run: |
          cd ${GITHUB_WORKSPACE}/pace
          mpiexec -np 6 python -m pace.run examples/configs/baroclinic_c48_no_out.yaml
